"""Add video details and fix ID name

Revision ID: 8137e3db19b7
Revises: 342d8f2fbab3
Create Date: 2026-04-15 09:49:37.820797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8137e3db19b7'
down_revision: Union[str, Sequence[str], None] = '342d8f2fbab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'url')
    op.drop_column('posts', 'thumbnail_url')
    # ### end Alembic commands ###
