"""Add connections posts and metrics

Revision ID: 8455b31b01b3
Revises: fab879f1496e
Create Date: 2026-04-13 20:59:42.033323

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8455b31b01b3'
down_revision: Union[str, Sequence[str], None] = 'fab879f1496e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
